### ISSUE TITLE
oddawaj moją grę!

### ISSUE THREAD

**Issue by wyjek** [derefff/titan#1]
ty chuju zajebany złodzieju polaczku oddawaj moją godność osobistą, to jest MOJA gra, sprawdź sobie datę utworzenia repo **testujemy markdowna** __fajne co__

**Comment by derefff** [comment]
thank you for your support <3 enjoy :D

**Comment by wyjek** [comment]
ty tu nie udawaj greka chuju zajebany żądam rękojmi i odszkodowania
